name: 'run'

on:
  push
  schedule:
    - cron: '0 4 * 1,2,6,7 1'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: 'setup python'
       uses: actions/setup-python@master
       with: 
         python-version: 3.7

     - name: main
       env:
         login_account: ${{ secrets.USERNAME }}
         password: ${{ secrets.PASSWORD }}
         mail_account: ${{ secrets.MAIL_ACCOUNT }}
         mail_key: ${{ secrets.MAIL_KEY }}
         score_term: ${{ secrets.TERM }}
       run: |
         pip3 install requests
         python ./score.py
