name: 'run'

on:
  push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: 'setup python'
       uses: actions/setup-python@master
       with: 
         python-version: 3.7
       
     - name: main
       env:
         sc_url: ${{ secrets.SCHOOL_URL }}
         login_account: ${{ secrets.USERNAME }}
         password: ${{ secrets.PASSWORD }}
         mail_account: ${{ secrets.mail_account }}
         mail_password: ${{ secrets.mail_password }}
       run: |
         pip3 install school_api
         python ./score.py